import CssBaseline from "@mui/material/CssBaseline"
import Box from "@mui/material/Box"
import { ThemeProvider, createTheme } from "@mui/material/styles"
import type { Metadata } from "next"
import { theme, themeOptions } from "./theme"
// import { Inter } from "next/font/google"

// const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

// const theme = createTheme(themeOptions)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body>{children}</body>
      </ThemeProvider>
    </html>
  )
}
